const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🔄 Updating backend IP configuration...\n');

try {
    // Get current IP address
    const ipOutput = execSync('ipconfig', { encoding: 'utf8' });
    const ipMatch = ipOutput.match(/IPv4 Address[.\s]*:\s*(\d+\.\d+\.\d+\.\d+)/);

    if (!ipMatch) {
        throw new Error('Could not detect IP address');
    }

    const currentIP = ipMatch[1];
    console.log(`✅ Detected IP: ${currentIP}`);

    // Update backend-config.json
    const configPath = path.join(__dirname, '../frontend/backend-config.json');
    const config = {
        ip: currentIP,
        lastUpdated: new Date().toISOString(),
        note: "Auto-generated by update-ip.js"
    };

    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    console.log(`✅ Updated: ${configPath}`);
    console.log('\n📤 Next step: Deploy to Firebase');
    console.log('   Run: firebase deploy --only hosting\n');

} catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
}
